import "./globals.css";
import Providers from "./Providers";
import { SocketProvider } from "./video-meeting/context/SocketProvider";


export const metadata = {
  title: "Google Meet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
      >
        <Providers>
          <SocketProvider>
        {children}
        </SocketProvider>
        </Providers>
      </body>
    </html>
  );
}
